# Generated by Django 5.2 on 2025-04-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Editor'), (3, 'Vendedor'), (4, 'Invitado')], default=4)),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
    ]
