# Generated by Django 5.2 on 2025-04-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
